<a href="https://colab.research.google.com/github/lancedsouza/LLM_fromScratch/blob/main/LLM_strat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
a=torch.tensor([2.0],requires_grad=True)
b = torch.tensor([3.0], requires_grad=True)

In [ ]:
# Add, multiply
c = a * b + 4
print(c)  # Tensor with computation graph

tensor([10.], grad_fn=<AddBackward0>)


In [ ]:
y_hat=torch.tensor([2.0],requires_grad=True)
y=torch.tensor([4.0])

In [ ]:
loss=(y_hat-y)**2
loss.backward()

In [ ]:
print(y_hat.grad)

tensor([-4.])


Training a neural network

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim


In [2]:
  pip install torch torchvision


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 80.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 56.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 38.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 95.7 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [3]:
# Original data
data = torch.tensor([
    [45.0, 150.0],   # Alice
    [75.0, 180.0],   # Bob
    [70.0, 175.0],   # Charlie
    [50.0, 145.0],   # Dana
])

# Step 1: Compute mean and std
mean = data.mean(dim=0)
std = data.std(dim=0)

# Step 2: Normalize
normalized_data = (data - mean) / std


In [4]:
normalized_data

tensor([[-1.0190, -0.7119],
        [ 1.0190,  0.9966],
        [ 0.6794,  0.7119],
        [-0.6794, -0.9966]])

In [5]:
# Labels: 1 = Female, 0 = Male
y = torch.tensor([
    [1.0],
    [0.0],
    [0.0],
    [1.0]
], dtype=torch.float32)

Step 2: Build a Simple Neural Network

What does super() mean?
super() is used to call the parent class's methods.
In your case:

python
Copy
Edit
class SimpleNN(nn.Module):
You're saying SimpleNN is a subclass of torch.nn.Module. That means it inherits all the functionality of PyTorch's neural network module class — which handles a lot of behind-the-scenes stuff like weight management, saving/loading models, GPU transfers, etc.

🛠 So super().__init__() means:
"Call the constructor (__init__ function) of nn.Module, the parent class."

This is necessary to properly set up all the internal mechanics that PyTorch needs to make your neural network work.

If you don’t call super().__init__(), PyTorch won’t know how to:

Track layers (self.fc1, self.fc2)

Calculate gradients

Use .to(device) to move model to GPU

Save/load model parameters

🔧 In plain English:
Imagine you’re building a custom robot (SimpleNN) based on a general robot blueprint (nn.Module).

You say:

python
Copy
Edit
class SimpleNN(nn.Module):
But if you don’t call:

python
Copy
Edit
super().__init__()
…you’re not telling the robot to initialize the blueprint correctly.
So its arms (layers), brain (optimizer), and sensors (autograd) won’t work.

🔁 Full context:
python
Copy
Edit
class SimpleNN(nn.Module):           # Inherit from nn.Module
    def __init__(self):              # Define constructor
        super().__init__()           # Call parent constructor (important!)
        self.fc1 = nn.Linear(2, 2)   # First layer
        self.fc2 = nn.Linear(2, 1)   # Output layer
✅ This ensures PyTorch tracks everything and the model behaves as expected.

In [6]:
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 2)  # input: 2 features (weight, height), output: 2 neurons
        self.fc2 = nn.Linear(2, 1)  # from 2 neurons to 1 output

    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))  # hidden layer with sigmoid
        x = torch.sigmoid(self.fc2(x))  # output layer with sigmoid
        return x


SyntaxError: unterminated string literal (detected at line 2) (ipython-input-7-1736479077.py, line 2)